package com.bohdanov.uilibrary.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF902FB4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF330045)
val md_theme_light_secondary = Color(0xFF69596C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF2DCF3)
val md_theme_light_onSecondaryContainer = Color(0xFF241727)
val md_theme_light_tertiary = Color(0xFF82524F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onTertiaryContainer = Color(0xFF331110)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEBDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747D)
val md_theme_light_inverseOnSurface = Color(0xFFF7EFF3)
val md_theme_light_inverseSurface = Color(0xFF332F33)
val md_theme_light_inversePrimary = Color(0xFFEEB1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF902FB4)
val md_theme_light_outlineVariant = Color(0xFFCFC3CD)
val md_theme_light_scrim = Color(0xFF000000)

val seed = Color(0xFF720097)
